### PR TITLE
Update import for api-gateway sdk

### PR DESCRIPTION
**Pull request by patrickdillon**
Updates imports of github.com/IBM/apigateway-go-sdk to import the package apigatewaycontrollerapiv1. The current state of the imports (before this series of PRs) results in issues when importing the provider:

```shell
$ go mod tidy
[...]
go: finding module for package github.com/IBM/apigateway-go-sdk/apigatewaycontrollerapiv1
github.com/openshift/installer/pkg/terraform/exec/plugins imports
    github.com/IBM-Cloud/terraform-provider-ibm/ibm imports
    github.com/IBM/apigateway-go-sdk tested by
    github.com/IBM/apigateway-go-sdk.test imports
    github.com/IBM/apigateway-go-sdk/apigatewaycontrollerapiv1: module github.com/IBM/apigateway-go-sdk@latest found (v0.0.0-20200414212859-416e5948678a), but does not contain package github.com/IBM/apigateway-go-sdk/apigatewaycontrollerapiv1
```

/hold
Depends on IBM/apigateway-go-sdk#3

This is ready for review but once IBM/apigateway-go-sdk#3 we can re-vendor and merge.

Please let me know if this is not the correct branch.

cc @jstuever @hasueki @BobbyRadford

### CODE REVIEW

**Comment by patrickdillon** [comment]
Also would appreciate any pointers if we want to get this upstream (which branch to open a PR against).

**Comment by patrickdillon** [comment]
/hold cancel 
IBM/apigateway-go-sdk#3 has merged

Testing vendoring against this PR worked successfully for me:
```shell
[padillon@thinkpad installer]$ go mod vendor
go: github.com/IBM-Cloud/terraform-provider-ibm@v1.26.2 requires
	github.com/IBM/apigateway-go-sdk@v0.0.0-20200414212859-416e5948678a requires
	github.com/IBM-Cloud/ibm-cloud-cli-sdk@v0.6.7: reading github.com/IBM-Cloud/ibm-cloud-cli-sdk/go.mod at revision v0.6.7: unknown revision v0.6.7
(reverse-i-search)`replace': go mod edit -replace=github.com/IBM/apigateway-go-sdk=github.com/patrickdillon/apigateway-go-sdk@pkg-apigatewaycontrollerapiv1 -^Cplace=github.com/IBM-Cloud/terraform-provider-ibm=github.com/patrickdillon/terraform-provider-ibm@import-apigatewaycontrollerapiv1
[padillon@thinkpad installer]$ go mod edit -replace=github.com/IBM-Cloud/terraform-provider-ibm=github.com/patrickdillon/terraform-provider-ibm@import-apigatewaycontrollerapiv1
[padillon@thinkpad installer]$ go mod tidy
warning: ignoring symlink /home/padillon/go/src/github.com/openshift/installer/pkg/asset/store/data
go: downloading github.com/patrickdillon/terraform-provider-ibm v1.26.3-0.20210714142329-b259f99d7d77
[padillon@thinkpad installer]$ go mod vendor
warning: ignoring symlink /home/padillon/go/src/github.com/openshift/installer/pkg/asset/store/data
```

**Comment by patrickdillon** [comment]
/reopen

Woops. Pushed the base branch :stuck_out_tongue_closed_eyes:

**Comment by patrickdillon** [comment]
/hold cancel
Should be all good.

**Review by hasueki — APPROVED** [review]

**Comment by hasueki** [comment]
PR to upstream repo opened: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2873

**Pull request merged**
